# Generated by Django 5.1.3 on 2025-01-31 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0002_groupmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmodel',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='user_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='group_members', to='level.groupmodel'),
        ),
    ]
