# Generated by Django 5.1.3 on 2025-03-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0004_customuser_age_customuser_birthdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birthdate',
        ),
    ]
